config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                       sessions: "users/sessions",
                       registrations: "users/registrations",
                     }
  namespace :users do
    devise_scope :user do
      post "/sign_in", :to => "sessions#create"
      post "/sign_up", :to => "registrations#create"
      delete "/sign_out", :to => "sessions#destroy"
    end
  end

  root to: "welcome#index"
  resources :users 
  post "/users/check_token", :to => "users#check_token"

  resources :celebrations

  resources :deals, only: [:show, :index] do
    get "/places", :to => "deals#places"
  end

  resources :places, only: [:show, :index]
end

app/models/celebration.rb
class Celebration < ApplicationRecord
  belongs_to :user
end

app/controllers/celebrations_controller.rb
class CelebrationsController < ApplicationController
  before_action :set_celebration, only: [:show, :edit, :update, :destroy]
  before_action :find_user, only: [:index]
  skip_before_action :verify_authenticity_token
  # GET /celebrations
  # GET /celebrations.json
  def index
    @celebrations = @user ? @user.celebrations : Celebration.all
  end

  # GET /celebrations/1
  # GET /celebrations/1.json
  def show
  end

  # GET /celebrations/new
  def new
    @celebration = Celebration.new
  end

  # GET /celebrations/1/edit
  def edit
  end

  # POST /celebrations
  # POST /celebrations.json
  def create
    @celebration = Celebration.new(celebration_params)

    respond_to do |format|
      if @celebration.save
        format.json { render :json => {:success => true, celebration: @celebration} }
        format.html { redirect_to @celebration, notice: "Celebration was successfully created." }
      else
        format.json { render :json => {:success => false, message: @celebration.errors} }
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /celebrations/1
  # PATCH/PUT /celebrations/1.json
  def update
    respond_to do |format|
      if @celebration.update(celebration_params)
        format.json { render :json => {:success => true, celebration: @celebration} }
        format.html { redirect_to @celebration, notice: "Celebration was successfully updated." }
      else
        format.json { render :json => {:success => false, message: @celebration.errors} }
        format.html { render :edit }
      end
    end
  end

  # DELETE /celebrations/1
  # DELETE /celebrations/1.json
  def destroy
    @celebration.destroy
    respond_to do |format|
      format.json { render :json => {:success => true, :message => "Celebration was destroyed"} }
      format.html { redirect_to celebrations_url, notice: "Celebration was successfully destroyed." }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_celebration
    @celebration = Celebration.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def celebration_params
    params.require(:celebration).permit(:user_id, :title, :date_celebration, :note)
  end

  def find_user
    if params[:user_id].present?
      @user = User.find(params[:user_id])
    end
  end
end

app/views/celebrations/_form.html.erb
<%= form_for(celebration) do |f| %>
  <% if celebration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(celebration.errors.count, "error") %> prohibited this celebration from being saved:</h2>

      <ul>
      <% celebration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>


  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>


  <div class="field">
    <%= f.label :date_celebration %>
    <%= f.date_field :date_celebration %>
  </div>


  <div class="field">
    <%= f.label :note %>
    <%= f.text_field :note %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/celebrations/edit.html.erb
<h1>Editing Celebration</h1>

<%= render 'form', celebration: @celebration %>

<%= link_to 'Show', @celebration %> |
<%= link_to 'Back', celebrations_path %>

app/views/celebrations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Celebrations</h1>

<table class=" tbl-header">
  <thead>
    <tr>
      <th scope="col">ID</th>      
      <th scope="col">User</th>
      <th scope="col">Title</th>
      <th scope="col">Date Celebration</th>
      <th scope="col">Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @celebrations.each do |celebration| %>
      <tr>
        <th scope="row"><%= celebration.id %></th>
        <td><%= celebration.user.name %></td>
        <td><%= celebration.title %></td>
        <td><%= celebration.date_celebration %></td>
        <td><%= celebration.note %></td>
        
        <td><%= link_to 'Show', celebration %></td>
        <td><%= link_to 'Edit', edit_celebration_path(celebration) %></td>
        <td><%= link_to 'Destroy', celebration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Celebration', new_celebration_path %>

app/views/celebrations/new.html.erb
<h1>New Celebration</h1>

<%= render 'form', celebration: @celebration %>

<%= link_to 'Back', celebrations_path %>

app/views/celebrations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_celebration_path(@celebration) %> |
<%= link_to 'Back', celebrations_path %>